/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Matthias Carlier
 */
public class GameSetup extends javax.swing.JPanel {

    /**
     * Creates new form GameSetup
     */
    public GameSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblChosenCard1 = new javax.swing.JLabel();
        lblChosenCard2 = new javax.swing.JLabel();
        lblChosenCard3 = new javax.swing.JLabel();
        lblChosenCard4 = new javax.swing.JLabel();
        lblChosenCard5 = new javax.swing.JLabel();
        lblChosenCard6 = new javax.swing.JLabel();
        lblChosenCard7 = new javax.swing.JLabel();
        lblChosenCard8 = new javax.swing.JLabel();
        lblChosenCard9 = new javax.swing.JLabel();
        lblChosenCard10 = new javax.swing.JLabel();
        lblActionCard1 = new javax.swing.JLabel();
        lblActionCard2 = new javax.swing.JLabel();
        lblActionCard3 = new javax.swing.JLabel();
        lblActionCard4 = new javax.swing.JLabel();
        lblActionCard5 = new javax.swing.JLabel();
        lblActionCard6 = new javax.swing.JLabel();
        lblActionCard7 = new javax.swing.JLabel();
        lblActionCard8 = new javax.swing.JLabel();
        lblActionCard9 = new javax.swing.JLabel();
        lblActionCard10 = new javax.swing.JLabel();

        lblLogo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblLogo.setText("Dominion");
        lblLogo.setToolTipText("");

        btnStartGame.setText("Start Game");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Chose Your Action Cards");

        btnCancel.setText("Cancel");

        jLabel2.setText("Chosen Cards");

        jLabel3.setText("Action Cards");

        lblChosenCard1.setText("lblChosenCard");

        lblChosenCard2.setText("lblChosenCard");

        lblChosenCard3.setText("lblChosenCard");

        lblChosenCard4.setText("lblChosenCard");

        lblChosenCard5.setText("lblChosenCard");

        lblChosenCard6.setText("lblChosenCard");

        lblChosenCard7.setText("lblChosenCard");

        lblChosenCard8.setText("lblChosenCard");

        lblChosenCard9.setText("lblChosenCard");

        lblChosenCard10.setText("lblChosenCard");

        lblActionCard1.setText("lblActionCard");

        lblActionCard2.setText("lblActionCard");

        lblActionCard3.setText("lblActionCard");

        lblActionCard4.setText("lblActionCard");

        lblActionCard5.setText("lblActionCard");

        lblActionCard6.setText("lblActionCard");

        lblActionCard7.setText("lblActionCard");

        lblActionCard8.setText("lblActionCard");

        lblActionCard9.setText("lblActionCard");

        lblActionCard10.setText("lblActionCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(lblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActionCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblActionCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblActionCard2)
                                .addGap(24, 24, 24)
                                .addComponent(lblActionCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblActionCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblActionCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStartGame)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblActionCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblActionCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnCancel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblActionCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblActionCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblChosenCard1)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard2)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard3)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard4)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard5))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblChosenCard6)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard7)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard8)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard9)
                                .addGap(18, 18, 18)
                                .addComponent(lblChosenCard10)))))
                .addGap(483, 483, 483))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lblLogo)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChosenCard1)
                    .addComponent(lblChosenCard2)
                    .addComponent(lblChosenCard3)
                    .addComponent(lblChosenCard4)
                    .addComponent(lblChosenCard5))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChosenCard6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChosenCard7)
                        .addComponent(lblChosenCard8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChosenCard10)
                        .addComponent(lblChosenCard9)))
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActionCard1)
                    .addComponent(lblActionCard3)
                    .addComponent(lblActionCard4)
                    .addComponent(lblActionCard5)
                    .addComponent(lblActionCard2))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActionCard6)
                    .addComponent(lblActionCard7)
                    .addComponent(lblActionCard8)
                    .addComponent(lblActionCard9)
                    .addComponent(lblActionCard10))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartGame)
                    .addComponent(btnCancel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblActionCard1;
    private javax.swing.JLabel lblActionCard10;
    private javax.swing.JLabel lblActionCard2;
    private javax.swing.JLabel lblActionCard3;
    private javax.swing.JLabel lblActionCard4;
    private javax.swing.JLabel lblActionCard5;
    private javax.swing.JLabel lblActionCard6;
    private javax.swing.JLabel lblActionCard7;
    private javax.swing.JLabel lblActionCard8;
    private javax.swing.JLabel lblActionCard9;
    private javax.swing.JLabel lblChosenCard1;
    private javax.swing.JLabel lblChosenCard10;
    private javax.swing.JLabel lblChosenCard2;
    private javax.swing.JLabel lblChosenCard3;
    private javax.swing.JLabel lblChosenCard4;
    private javax.swing.JLabel lblChosenCard5;
    private javax.swing.JLabel lblChosenCard6;
    private javax.swing.JLabel lblChosenCard7;
    private javax.swing.JLabel lblChosenCard8;
    private javax.swing.JLabel lblChosenCard9;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
