/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Matthias Carlier
 */
public class Game extends javax.swing.JPanel {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayerName2 = new javax.swing.JLabel();
        lblAvaterPlayer2 = new javax.swing.JLabel();
        lblPlayerName3 = new javax.swing.JLabel();
        lblAvaterPlayer3 = new javax.swing.JLabel();
        lblPlayerName4 = new javax.swing.JLabel();
        lblAvaterPlayer4 = new javax.swing.JLabel();
        lblActionCard2 = new javax.swing.JLabel();
        lblActionCard3 = new javax.swing.JLabel();
        lblActionCard4 = new javax.swing.JLabel();
        lblActionCard5 = new javax.swing.JLabel();
        lblActionCard6 = new javax.swing.JLabel();
        lblActionCard7 = new javax.swing.JLabel();
        lblActionCard8 = new javax.swing.JLabel();
        lblActionCard9 = new javax.swing.JLabel();
        lblActionCard10 = new javax.swing.JLabel();
        lblActionCard1 = new javax.swing.JLabel();
        lblVPPoint1 = new javax.swing.JLabel();
        lblVPPoint2 = new javax.swing.JLabel();
        lblVPPoint3 = new javax.swing.JLabel();
        lblVPPoint4 = new javax.swing.JLabel();
        lblCoin1 = new javax.swing.JLabel();
        lblCoin2 = new javax.swing.JLabel();
        lblCoin3 = new javax.swing.JLabel();
        lblPlayedCard1 = new javax.swing.JLabel();
        lblPlayedCard2 = new javax.swing.JLabel();
        lblPlayedCard3 = new javax.swing.JLabel();
        lblTrash = new javax.swing.JLabel();
        btnResign = new javax.swing.JButton();
        btnManual1 = new javax.swing.JButton();
        lblHand1 = new javax.swing.JLabel();
        lblHand2 = new javax.swing.JLabel();
        lblHand3 = new javax.swing.JLabel();
        lblHand4 = new javax.swing.JLabel();
        lblHand5 = new javax.swing.JLabel();
        lblPlayerName1 = new javax.swing.JLabel();
        lblAvaterPlayer1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblActions = new javax.swing.JLabel();
        lblBuys = new javax.swing.JLabel();
        lblCoins = new javax.swing.JLabel();
        btnEndTurn = new javax.swing.JButton();
        btnPlayTreasure1 = new javax.swing.JButton();

        lblPlayerName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlayerName2.setText("Player2");

        lblAvaterPlayer2.setText("Avatar");

        lblPlayerName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlayerName3.setText("Player3");

        lblAvaterPlayer3.setText("Avatar");

        lblPlayerName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlayerName4.setText("Player4");

        lblAvaterPlayer4.setText("Avatar");

        lblActionCard2.setText("lblActionCard");

        lblActionCard3.setText("lblActionCard");

        lblActionCard4.setText("lblActionCard");

        lblActionCard5.setText("lblActionCard");

        lblActionCard6.setText("lblActionCard");

        lblActionCard7.setText("lblActionCard");

        lblActionCard8.setText("lblActionCard");

        lblActionCard9.setText("lblActionCard");

        lblActionCard10.setText("lblActionCard");

        lblActionCard1.setText("lblActionCard");

        lblVPPoint1.setText("lblVPPoint1");

        lblVPPoint2.setText("lblVPPoint2");

        lblVPPoint3.setText("lblVPPoint3");

        lblVPPoint4.setText("lblVPPoint4");

        lblCoin1.setText("lblCoin1");

        lblCoin2.setText("lblCoin2");

        lblCoin3.setText("lblCoin3");

        lblPlayedCard1.setText("lblPlayedCard1");

        lblPlayedCard2.setText("lblPlayedCard2");

        lblPlayedCard3.setText("lblPlayedCard3");

        lblTrash.setText("Trash");

        btnResign.setText("X");

        btnManual1.setText("?");

        lblHand1.setText("Hand1");

        lblHand2.setText("Hand1");

        lblHand3.setText("Hand1");

        lblHand4.setText("Hand1");

        lblHand5.setText("Hand1");

        lblPlayerName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlayerName1.setText("Player1");

        lblAvaterPlayer1.setText("Avatar");

        jLabel1.setText("Actions:");

        jLabel2.setText("Buys:");

        jLabel3.setText("Coins:");

        lblActions.setText("0");

        lblBuys.setText("0");

        lblCoins.setText("0");

        btnEndTurn.setText("End Turn");

        btnPlayTreasure1.setText("Play All Treasure");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvaterPlayer2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPlayerName2)
                        .addGap(350, 350, 350)
                        .addComponent(lblAvaterPlayer3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPlayerName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvaterPlayer4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPlayerName4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvaterPlayer1)
                                .addGap(18, 18, 18)
                                .addComponent(lblPlayerName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCoin2)
                                            .addGap(254, 254, 254)
                                            .addComponent(lblActionCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCoin1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblActionCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblCoin3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCoins)
                                            .addComponent(lblBuys)
                                            .addComponent(lblActions))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblActionCard2)
                                        .addGap(24, 24, 24)
                                        .addComponent(lblActionCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblActionCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblActionCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblActionCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblActionCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPlayedCard1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblPlayedCard2)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblActionCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblActionCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblPlayedCard3)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblHand1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHand2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHand3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHand4)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHand5)
                                        .addGap(112, 112, 112)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(btnEndTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrash)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblVPPoint4)
                                .addComponent(lblVPPoint3)
                                .addComponent(lblVPPoint1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblVPPoint2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btnResign))))
                .addGap(18, 18, 18)
                .addComponent(btnManual1)
                .addGap(77, 77, 77))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(903, Short.MAX_VALUE)
                    .addComponent(btnPlayTreasure1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(240, 240, 240)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerName2)
                    .addComponent(lblAvaterPlayer2)
                    .addComponent(lblPlayerName3)
                    .addComponent(lblAvaterPlayer3)
                    .addComponent(lblPlayerName4)
                    .addComponent(lblAvaterPlayer4))
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActionCard2)
                    .addComponent(lblActionCard1)
                    .addComponent(lblActionCard3)
                    .addComponent(lblActionCard4)
                    .addComponent(lblActionCard5)
                    .addComponent(lblVPPoint1)
                    .addComponent(lblCoin1))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActionCard6)
                    .addComponent(lblActionCard7)
                    .addComponent(lblActionCard8)
                    .addComponent(lblActionCard9)
                    .addComponent(lblActionCard10)
                    .addComponent(lblVPPoint2)
                    .addComponent(lblCoin2))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVPPoint3)
                    .addComponent(lblCoin3))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVPPoint4)
                    .addComponent(lblPlayedCard1)
                    .addComponent(lblPlayedCard2)
                    .addComponent(lblPlayedCard3)
                    .addComponent(jLabel1)
                    .addComponent(lblActions)
                    .addComponent(btnEndTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBuys))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCoins))
                .addGap(33, 33, 33)
                .addComponent(lblTrash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHand1)
                    .addComponent(lblHand2)
                    .addComponent(lblHand3)
                    .addComponent(lblHand4)
                    .addComponent(lblHand5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResign, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManual1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayerName1)
                    .addComponent(lblAvaterPlayer1))
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(789, Short.MAX_VALUE)
                    .addComponent(btnPlayTreasure1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndTurn;
    private javax.swing.JButton btnManual1;
    private javax.swing.JButton btnPlayTreasure1;
    private javax.swing.JButton btnResign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblActionCard1;
    private javax.swing.JLabel lblActionCard10;
    private javax.swing.JLabel lblActionCard2;
    private javax.swing.JLabel lblActionCard3;
    private javax.swing.JLabel lblActionCard4;
    private javax.swing.JLabel lblActionCard5;
    private javax.swing.JLabel lblActionCard6;
    private javax.swing.JLabel lblActionCard7;
    private javax.swing.JLabel lblActionCard8;
    private javax.swing.JLabel lblActionCard9;
    private javax.swing.JLabel lblActions;
    private javax.swing.JLabel lblAvaterPlayer1;
    private javax.swing.JLabel lblAvaterPlayer2;
    private javax.swing.JLabel lblAvaterPlayer3;
    private javax.swing.JLabel lblAvaterPlayer4;
    private javax.swing.JLabel lblBuys;
    private javax.swing.JLabel lblCoin1;
    private javax.swing.JLabel lblCoin2;
    private javax.swing.JLabel lblCoin3;
    private javax.swing.JLabel lblCoins;
    private javax.swing.JLabel lblHand1;
    private javax.swing.JLabel lblHand2;
    private javax.swing.JLabel lblHand3;
    private javax.swing.JLabel lblHand4;
    private javax.swing.JLabel lblHand5;
    private javax.swing.JLabel lblPlayedCard1;
    private javax.swing.JLabel lblPlayedCard2;
    private javax.swing.JLabel lblPlayedCard3;
    private javax.swing.JLabel lblPlayerName1;
    private javax.swing.JLabel lblPlayerName2;
    private javax.swing.JLabel lblPlayerName3;
    private javax.swing.JLabel lblPlayerName4;
    private javax.swing.JLabel lblTrash;
    private javax.swing.JLabel lblVPPoint1;
    private javax.swing.JLabel lblVPPoint2;
    private javax.swing.JLabel lblVPPoint3;
    private javax.swing.JLabel lblVPPoint4;
    // End of variables declaration//GEN-END:variables
}
